version: "3.9"

services:
  php:
    image: webdevops/php-nginx:8.1-alpine
    volumes:
      - ./:/app
    ports:
      - "0.0.0.0:80:80"
    working_dir: /app
    environment:
      WEB_DOCUMENT_INDEX: "public/index.php"
  redis:
    image: redis:7.0.9-alpine
    volumes:
      - ./.redis:/data
    ports:
      - "127.0.0.1:6379:6379"